version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: donamarialittlestore
    command: node app.js
    ports:
        - 3000:3000
    depends_on:
        - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
        - 27017:27017
